### ISSUE TITLE
py: Remove the pin to pyln-testing and pyln-client

### ISSUE THREAD

**Issue by cdecker** [Blockstream/greenlight#389] opened 2024-03-13 15:57 UTC
There is a change in the API between v23.11 and v24.02, causing `gl-testing` to fail.
@Randy808 temporarily pinned them to the latest working version, but we should re-establish compatibility with the latest version asap.

**Comment by ErikDeSmedt** [comment] 2024-03-20 09:30
I'll take this one

**Comment by ErikDeSmedt** [comment] 2024-03-20 10:10
For `pyln-testing` the problem is situated in the `--developer`-flag which was introduced in `v23.11`. In this release the `--developer`-flag was introduced as a replacement for compile-time options.

It breaks `pyln-testing` when using pre-`v23.11` versions of Core Lightning. Pre-`v23.11`-nodes will stop with an error-message indicating the `--developer` flag is not supported.

**Comment by nepet** [comment] 2024-08-28 13:33
I'll close this for now as the original problem seems to be resolved -> `gl-testing` uses:
  - pyln-testing = "==24.02"
 - pyln-client = "==24.02"

**Closed by nepet** 2024-08-28 13:33 UTC
