### ISSUE TITLE
Recover fails occasionally with bad certificate

### ISSUE THREAD

**Issue by roeierez** [Blockstream/greenlight#224] opened 2023-07-28 21:50 UTC
I have noticed that it happens when the node is not scheduled, not consistent.
Attaching the program I am using to reproduce it.
[recover.tar.gz](https://github.com/Blockstream/greenlight/files/12198683/recover.tar.gz)

**Comment by cdecker** [comment] 2023-07-31 14:03
I think we found the issue independently and addressed it, and I now can't reproduce the issue with your code (thanks for the repro example by the way, that made testing for the issue much much easier for us).

The issue we were facing was the following: the node domain (`gl1...nodes.gl.blckstrm.com`) is fronted by a reverse proxy that knows how to talk to the scheduler to locate a node if it is already running, and schedule it if it is not. That proxy uses SNI to detect the node the caller is attempting to contact (not decrypting the payload). It includes a cache to keep the interactions with the scheduler in check, however it can end up caching the resolution beyond the lifetime of the node. The node would get preempted, and potentially another node would get scheduled in the slot. The next connection to the node domain would still get routed to the old location, where a different node with different certificates would now be running. Since the certificates do not match the user certificates (both client cert and node cert need to be part of the user cert tree) we'd end up with either a `transport error` (if no node had been scheduled in the slot yet) or a `BadCertificate` (if a new node had been scheduled) error.

We disabled the cache, and we should no longer forward to stale allocations anymore. I'll leave this issue open for a couple more days and close if the issue doesn't manifest anymore.

**Comment by cdecker** [comment] 2023-08-03 14:14
After turning the mitigation off (accidentally) and seeing the problem reappear, and then disappear with the mitigation re-deployed, I am now rather confident that this issue has been addressed :D 

Closing, but if it reappears we can re-open :-)

**Closed by cdecker** 2023-08-03 14:14 UTC
Labels: state::verifying
