### ISSUE TITLE
No such file or directory gRPC result

### ISSUE THREAD

**Issue by roeierez** [Blockstream/greenlight#295] opened 2023-10-15 11:37 UTC
I get the following error sometimes when recovering a node and then invoking the gRPC interface:

`status: Internal, message: "No such file or directory (os error 2)", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Sun, 15 Oct 2023 11:23:57 GMT", "content-length": "0"} }
`

node id: 03d7854ada08c92919223e95e02da0be2695c2354d66448d9cb6a451aaed57b3b0
time: 15/10/2023 11:23:47 UTC

**Comment by ok300** [comment] 2023-10-18 13:11
I just saw it too, it was at the same time as

```
[2023-10-18 13:00:11.726 ERROR breez_sdk_core::backup:332] Sync failed: status: Unknown, message: "Service was not ready: transport error", details: [], metadata: MetadataMap { headers: {} }
[2023-10-18 13:00:11.726 ERROR breez_sdk_core::backup:255] backup sync failed status: Unknown, message: "Service was not ready: transport error", details: [], metadata: MetadataMap { headers: {} }
```

Looks like its related to `sync` and `backup` dying with a transport error.

**Comment by ok300** [comment] 2023-10-18 13:51
Turns out this exact error can happen when `tonic` and `tonic-build` use different versions: https://github.com/hyperium/tonic/issues/1062

I checked our dependency tree and found that `cln-grpc` is providing `tonic v0.8.3` and `tonic-build v0.8.4`:

https://github.com/Blockstream/greenlight/blob/f91390734fc8a3044812f05ff8d0e102660189bb/libs/Cargo.lock#L555-L556

Just to rule this out as a potential root cause, @cdecker could you please align the `tonic` and `tonic-build` versions?

**Comment by ok300** [comment] 2023-10-18 15:11
It occurred in another setup with the same `sync` and `backup` behavior as above, and this time with node logs such as:

```
[2023-10-18 15:00:04.062 DEBUG breez_sdk_core::breez_services:1104] node-logs: UNUSUAL plugin-gl-plugin-internal: JSON-RPC interface not yet available. Delaying 50ms. IoError(Os { code: 2, kind: NotFound, message: \"No such file or directory\" })
[2023-10-18 15:00:04.062 DEBUG breez_sdk_core::breez_services:1104] node-logs: UNUSUAL plugin-gl-plugin-internal: JSON-RPC interface not yet available. Delaying 50ms. IoError(Os { code: 2, kind: NotFound, message: \"No such file or directory\" })
[2023-10-18 15:00:04.062 DEBUG breez_sdk_core::breez_services:1104] node-logs: UNUSUAL plugin-gl-plugin-internal: JSON-RPC interface not yet available. Delaying 50ms. IoError(Os { code: 2, kind: NotFound, message: \"No such file or directory\" })
```

**Comment by cdecker** [comment] 2023-12-12 12:56
The `no such file or directory` issue is a sign of an overloaded host or bitcoind (the latter is unlikely). When receiving a grpc command that we ought to forward to the JSON-RPC we will wait for up to 10s for the lightning-rpc  file to appear (that's the JSON-RPC UDS). If the 10s expire we let the RPC through anyway, allowing it to fail "normally".
So the node hasn't opened its JSON-RPC socket for at least 10s. This is usually because it hasn't finished checking the subdaemons, or it is very slow in downloading the first block.
I'll reduce the load on the hosts, and that should reduce the number of occurrences, longer term we are benchmarking and reordering the startup sequence (not just for pay) to solve this once and for all.

**Comment by cdecker** [comment] 2024-01-26 14:17
We have deployed the resource partitioning on Tuesday 2024-01-23. This separates nodes performing blocksync from the interactive nodes that users are interacting with. They have fundamentally different requirements (blocksync may peg the CPU to 100% fine, but interactive needs some headroom for bursts).

This should address the vast majority of slow startups, and I am closing this issue as as addressed. Should the issue return, please open a new issue.

**Closed by cdecker** 2024-01-26 14:17 UTC
Labels: perf, component::node, phase::startup
